### ISSUE TITLE
Cancellation of execution

### ISSUE THREAD

**Issue by ktoto** [cerebral/function-tree#5]
For example, i have this tree
```js
var tree = [
    someActionA,
    longActionAndBigData,
   someActionB
]
```
can i cancel execution in some point of this tree? For example, between `longActionAndBigData` and `someActionB`?

**Comment by christianalfoni** [comment]
Hi @ktoto, 

This is planned to be implemented actually. When it is ready it will work something like this:

```js
function someFunc({execution}) {
  execution.abort()
}
```

The tree will then stop and an `aborted` event will be triggered. Will come back to this soon :)

**Comment by ktoto** [comment]
I'll be waiting :+1:

**Comment by christianalfoni** [comment]
This is now released :) check updated docs
