### ISSUE TITLE
Running the demos?

### ISSUE THREAD

**Issue by ericclemmons** [cerebral/function-tree#8]
Attempting to run demos in **Version 56.0.2901.0 canary (64-bit)** resulted in this warning in the console (and the demos not working):
> Request was blocked by DevTools: "http://localhost:3000/".

```
$ npm i
$ npm run demo:mobx
```

This was a problem with all demos.

**Comment by ericclemmons** [comment]
Ok, _now_ it seems to be running (**no idea**), but the only content on the page is:

```html

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <title>Demo: redux</title>
    <style>
      html, body {
        height: 100%;
        background-color: #EFEFEF;
      }
    </style>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
```

No scripts or anything...

**Comment by ericclemmons** [comment]
Ah, I think I know why...going to just fork & fix :)

**Comment by Guria** [comment]
as noted in #9 function-tree now is part of cerebral monorepo
